//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SPResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Create_ProductCode.
        /// </summary>
        internal static string Create_ProductCode {
            get {
                return ResourceManager.GetString("Create_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Create_StoreCode.
        /// </summary>
        internal static string Create_StoreCode {
            get {
                return ResourceManager.GetString("Create_StoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_AccountEmail.
        /// </summary>
        internal static string Delete_AccountEmail {
            get {
                return ResourceManager.GetString("Delete_AccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_InviteEmailDetails.
        /// </summary>
        internal static string Delete_InviteEmailDetails {
            get {
                return ResourceManager.GetString("Delete_InviteEmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_Review_V1.
        /// </summary>
        internal static string Delete_Review {
            get {
                return ResourceManager.GetString("Delete_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ReviewComment.
        /// </summary>
        internal static string Delete_ReviewComment {
            get {
                return ResourceManager.GetString("Delete_ReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ReviewCommentLike.
        /// </summary>
        internal static string Delete_ReviewCommentLike {
            get {
                return ResourceManager.GetString("Delete_ReviewCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ReviewCommentMedia.
        /// </summary>
        internal static string Delete_ReviewCommentMedia {
            get {
                return ResourceManager.GetString("Delete_ReviewCommentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ReviewLike.
        /// </summary>
        internal static string Delete_ReviewLike {
            get {
                return ResourceManager.GetString("Delete_ReviewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ReviewReferences.
        /// </summary>
        internal static string Delete_ReviewReferences {
            get {
                return ResourceManager.GetString("Delete_ReviewReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_SecondaryEmail.
        /// </summary>
        internal static string Delete_SecondaryEmail {
            get {
                return ResourceManager.GetString("Delete_SecondaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_ShareEmailDetails_V1.
        /// </summary>
        internal static string Delete_ShareEmailDetails {
            get {
                return ResourceManager.GetString("Delete_ShareEmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StoreCoverPhoto.
        /// </summary>
        internal static string Delete_StoreCoverPhoto {
            get {
                return ResourceManager.GetString("Delete_StoreCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StoreCoverPhotoMedia_v1.
        /// </summary>
        internal static string Delete_StoreCoverPhotoMedia {
            get {
                return ResourceManager.GetString("Delete_StoreCoverPhotoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePost_v1.
        /// </summary>
        internal static string Delete_StorePost {
            get {
                return ResourceManager.GetString("Delete_StorePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePostComment.
        /// </summary>
        internal static string Delete_StorePostComment {
            get {
                return ResourceManager.GetString("Delete_StorePostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePostCommentLike.
        /// </summary>
        internal static string Delete_StorePostCommentLike {
            get {
                return ResourceManager.GetString("Delete_StorePostCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePostCommentMedia.
        /// </summary>
        internal static string Delete_StorePostCommentMedia {
            get {
                return ResourceManager.GetString("Delete_StorePostCommentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePostLike.
        /// </summary>
        internal static string Delete_StorePostLike {
            get {
                return ResourceManager.GetString("Delete_StorePostLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StorePostMedia_v1.
        /// </summary>
        internal static string Delete_StorePostMedia {
            get {
                return ResourceManager.GetString("Delete_StorePostMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StoreProfilePicture.
        /// </summary>
        internal static string Delete_StoreProfilePicture {
            get {
                return ResourceManager.GetString("Delete_StoreProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_StoreProfilePictureMedia.
        /// </summary>
        internal static string Delete_StoreProfilePictureMedia {
            get {
                return ResourceManager.GetString("Delete_StoreProfilePictureMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_UserAddress.
        /// </summary>
        internal static string Delete_UserAddress {
            get {
                return ResourceManager.GetString("Delete_UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Delete_UserProfilePicture.
        /// </summary>
        internal static string Delete_UserProfilePicture {
            get {
                return ResourceManager.GetString("Delete_UserProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Disable_Badge.
        /// </summary>
        internal static string Disable_Badge {
            get {
                return ResourceManager.GetString("Disable_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_FilterProductMedia.
        /// </summary>
        internal static string FilterProductMedia {
            get {
                return ResourceManager.GetString("FilterProductMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_AccountDeactivationReasons.
        /// </summary>
        internal static string Get_AccountDeactivationReasons {
            get {
                return ResourceManager.GetString("Get_AccountDeactivationReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_AccountDeletionDetails.
        /// </summary>
        internal static string Get_AccountDeletionDetails {
            get {
                return ResourceManager.GetString("Get_AccountDeletionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_AdressForPayment_v2.
        /// </summary>
        internal static string Get_Address_Payment {
            get {
                return ResourceManager.GetString("Get_Address_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_AllReviews_V3.
        /// </summary>
        internal static string Get_AllReviews {
            get {
                return ResourceManager.GetString("Get_AllReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_Buckets_v3.
        /// </summary>
        internal static string Get_Buckets {
            get {
                return ResourceManager.GetString("Get_Buckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_BuyAgainDetails.
        /// </summary>
        internal static string Get_BuyAgainDetails {
            get {
                return ResourceManager.GetString("Get_BuyAgainDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_CreateReviewDetails_V3.
        /// </summary>
        internal static string Get_CreateReviewDetails {
            get {
                return ResourceManager.GetString("Get_CreateReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_CustomGenderList.
        /// </summary>
        internal static string Get_CustomGenderList {
            get {
                return ResourceManager.GetString("Get_CustomGenderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_EIN.
        /// </summary>
        internal static string Get_EIN {
            get {
                return ResourceManager.GetString("Get_EIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_EmailDetails.
        /// </summary>
        internal static string Get_EmailDetails {
            get {
                return ResourceManager.GetString("Get_EmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_EmailMapWithAnotherAccount.
        /// </summary>
        internal static string Get_EmailMapWithAnotherAccount {
            get {
                return ResourceManager.GetString("Get_EmailMapWithAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_EntityDetailsForReviewGA.
        /// </summary>
        internal static string Get_EntityDetailsForReviewGA {
            get {
                return ResourceManager.GetString("Get_EntityDetailsForReviewGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_EntityStatusForReviewBySIN_V2.
        /// </summary>
        internal static string Get_EntityStatusForReviewBySIN {
            get {
                return ResourceManager.GetString("Get_EntityStatusForReviewBySIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_InviteGroupList.
        /// </summary>
        internal static string Get_InviteGroupWithCount {
            get {
                return ResourceManager.GetString("Get_InviteGroupWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_InviteSuggestedUserContactList_v1.
        /// </summary>
        internal static string Get_InviteSuggestedUserContactList {
            get {
                return ResourceManager.GetString("Get_InviteSuggestedUserContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_InviteGroupContacts.
        /// </summary>
        internal static string Get_InviteUserContactList {
            get {
                return ResourceManager.GetString("Get_InviteUserContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_InvoiceDetails_v7.
        /// </summary>
        internal static string Get_InvoiceDetails {
            get {
                return ResourceManager.GetString("Get_InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_NameDetails.
        /// </summary>
        internal static string Get_NameDetails {
            get {
                return ResourceManager.GetString("Get_NameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderConfirmationDetails_v6.
        /// </summary>
        internal static string Get_OrderConfirmationDetails {
            get {
                return ResourceManager.GetString("Get_OrderConfirmationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderDetailsForRefund.
        /// </summary>
        internal static string Get_OrderDetailsForRefund {
            get {
                return ResourceManager.GetString("Get_OrderDetailsForRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderDetailsByOrderID.
        /// </summary>
        internal static string Get_OrderItemsDetails {
            get {
                return ResourceManager.GetString("Get_OrderItemsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderReturnReasonDetails.
        /// </summary>
        internal static string Get_OrderReturnReasonDetails {
            get {
                return ResourceManager.GetString("Get_OrderReturnReasonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderReviewDetails_v8.
        /// </summary>
        internal static string Get_OrderReview {
            get {
                return ResourceManager.GetString("Get_OrderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OrderDetails_v7.
        /// </summary>
        internal static string Get_OrderReviewData {
            get {
                return ResourceManager.GetString("Get_OrderReviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_OverviewReviews_V3.
        /// </summary>
        internal static string Get_OverviewReviews {
            get {
                return ResourceManager.GetString("Get_OverviewReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_PasswordDetails.
        /// </summary>
        internal static string Get_PasswordDetails {
            get {
                return ResourceManager.GetString("Get_PasswordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_PersonalInfo_V1.
        /// </summary>
        internal static string Get_PersonalInfo {
            get {
                return ResourceManager.GetString("Get_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ProductAttributeDetails_V1.
        /// </summary>
        internal static string Get_ProductAttributeDetails {
            get {
                return ResourceManager.GetString("Get_ProductAttributeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ProductExists_v4.
        /// </summary>
        internal static string Get_ProductExists {
            get {
                return ResourceManager.GetString("Get_ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ProductPostForESIndex_V3.
        /// </summary>
        internal static string Get_ProductPostForESIndex {
            get {
                return ResourceManager.GetString("Get_ProductPostForESIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ProfileCompletionPercentage_v1.
        /// </summary>
        internal static string Get_ProfileCompletionPercentage {
            get {
                return ResourceManager.GetString("Get_ProfileCompletionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_RatingStats_V1.
        /// </summary>
        internal static string Get_RatingStats {
            get {
                return ResourceManager.GetString("Get_RatingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReturnDetailsForMail.
        /// </summary>
        internal static string Get_ReturnDetailsForMail {
            get {
                return ResourceManager.GetString("Get_ReturnDetailsForMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReturnItemDetails.
        /// </summary>
        internal static string Get_ReturnItemDetails {
            get {
                return ResourceManager.GetString("Get_ReturnItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewCommentDetails.
        /// </summary>
        internal static string Get_ReviewCommentDetails {
            get {
                return ResourceManager.GetString("Get_ReviewCommentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewCommentHistoryDetails.
        /// </summary>
        internal static string Get_ReviewCommentHistoryDetails {
            get {
                return ResourceManager.GetString("Get_ReviewCommentHistoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewCommentLike.
        /// </summary>
        internal static string Get_ReviewCommentLike {
            get {
                return ResourceManager.GetString("Get_ReviewCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewCommentReplyDetails.
        /// </summary>
        internal static string Get_ReviewCommentReplyDetails {
            get {
                return ResourceManager.GetString("Get_ReviewCommentReplyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewLike.
        /// </summary>
        internal static string Get_ReviewLike {
            get {
                return ResourceManager.GetString("Get_ReviewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ReviewLikeCommentShareEntity.
        /// </summary>
        internal static string Get_ReviewLikeCommentShareEntity {
            get {
                return ResourceManager.GetString("Get_ReviewLikeCommentShareEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SettingsAccountInfo.
        /// </summary>
        internal static string Get_SettingsAccountInfo {
            get {
                return ResourceManager.GetString("Get_SettingsAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareFollowersDetails.
        /// </summary>
        internal static string Get_ShareFollowersDetails {
            get {
                return ResourceManager.GetString("Get_ShareFollowersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareGroupContacts_v1.
        /// </summary>
        internal static string Get_ShareGroupContacts {
            get {
                return ResourceManager.GetString("Get_ShareGroupContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareGroupList.
        /// </summary>
        internal static string Get_ShareGroupList {
            get {
                return ResourceManager.GetString("Get_ShareGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareSuggestedGroupContacts_v1.
        /// </summary>
        internal static string Get_ShareSuggestedGroupContacts {
            get {
                return ResourceManager.GetString("Get_ShareSuggestedGroupContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareTemplateDetails_v1.
        /// </summary>
        internal static string Get_ShareTemplateDetails {
            get {
                return ResourceManager.GetString("Get_ShareTemplateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_ShareUnsubscribeName.
        /// </summary>
        internal static string Get_ShareUnsubscribeName {
            get {
                return ResourceManager.GetString("Get_ShareUnsubscribeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SingleReview_V3.
        /// </summary>
        internal static string Get_SingleReview {
            get {
                return ResourceManager.GetString("Get_SingleReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SocialMediaMaster.
        /// </summary>
        internal static string Get_SocialMediaMaster {
            get {
                return ResourceManager.GetString("Get_SocialMediaMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SSINCreateDetails.
        /// </summary>
        internal static string Get_SSINCreateDetails {
            get {
                return ResourceManager.GetString("Get_SSINCreateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StatesByCountryID.
        /// </summary>
        internal static string Get_StatesByCountryID {
            get {
                return ResourceManager.GetString("Get_StatesByCountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreAbout.
        /// </summary>
        internal static string Get_StoreAbout {
            get {
                return ResourceManager.GetString("Get_StoreAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreAnalyticsMetricDetails.
        /// </summary>
        internal static string Get_StoreAnalyticsMetricDetails {
            get {
                return ResourceManager.GetString("Get_StoreAnalyticsMetricDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreCoverPhoto.
        /// </summary>
        internal static string Get_StoreCoverPhoto {
            get {
                return ResourceManager.GetString("Get_StoreCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreCreated.
        /// </summary>
        internal static string Get_StoreCreated {
            get {
                return ResourceManager.GetString("Get_StoreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreDetails_V2.
        /// </summary>
        internal static string Get_StoreDetails {
            get {
                return ResourceManager.GetString("Get_StoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreExists.
        /// </summary>
        internal static string Get_StoreExists {
            get {
                return ResourceManager.GetString("Get_StoreExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreNameDetails.
        /// </summary>
        internal static string Get_StoreNameDetails {
            get {
                return ResourceManager.GetString("Get_StoreNameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePhotoByIDs.
        /// </summary>
        internal static string Get_StorePhotoByIDs {
            get {
                return ResourceManager.GetString("Get_StorePhotoByIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePhotoIDs.
        /// </summary>
        internal static string Get_StorePhotoIDs {
            get {
                return ResourceManager.GetString("Get_StorePhotoIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostCommentDetails.
        /// </summary>
        internal static string Get_StorePostCommentDetails {
            get {
                return ResourceManager.GetString("Get_StorePostCommentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostCommentHistoryDetails.
        /// </summary>
        internal static string Get_StorePostCommentHistoryDetails {
            get {
                return ResourceManager.GetString("Get_StorePostCommentHistoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostCommentLike.
        /// </summary>
        internal static string Get_StorePostCommentLike {
            get {
                return ResourceManager.GetString("Get_StorePostCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostCommentReplyDetails.
        /// </summary>
        internal static string Get_StorePostCommentReplyDetails {
            get {
                return ResourceManager.GetString("Get_StorePostCommentReplyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostDetails.
        /// </summary>
        internal static string Get_StorePostDetails {
            get {
                return ResourceManager.GetString("Get_StorePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostLike.
        /// </summary>
        internal static string Get_StorePostLike {
            get {
                return ResourceManager.GetString("Get_StorePostLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StorePostLikeCommentShareEntity.
        /// </summary>
        internal static string Get_StorePostLikeCommentShareEntity {
            get {
                return ResourceManager.GetString("Get_StorePostLikeCommentShareEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreProfileDetails.
        /// </summary>
        internal static string Get_StoreProfileDetails {
            get {
                return ResourceManager.GetString("Get_StoreProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreQrRedirectDetails.
        /// </summary>
        internal static string Get_StoreQrRedirectDetails {
            get {
                return ResourceManager.GetString("Get_StoreQrRedirectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreSinglePostDetails.
        /// </summary>
        internal static string Get_StoreSinglePostDetails {
            get {
                return ResourceManager.GetString("Get_StoreSinglePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreTopDetails_v1.
        /// </summary>
        internal static string Get_StoreTopDetails {
            get {
                return ResourceManager.GetString("Get_StoreTopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_StoreUsernameDetails.
        /// </summary>
        internal static string Get_StoreUsernameDetails {
            get {
                return ResourceManager.GetString("Get_StoreUsernameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SubscriptionPlanDetails.
        /// </summary>
        internal static string Get_SubscriptionPlanDetails {
            get {
                return ResourceManager.GetString("Get_SubscriptionPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_SubscriptionStatus.
        /// </summary>
        internal static string Get_SubscriptionStatus {
            get {
                return ResourceManager.GetString("Get_SubscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_TimeZoneByIANA.
        /// </summary>
        internal static string Get_TimeZoneByIANA {
            get {
                return ResourceManager.GetString("Get_TimeZoneByIANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_TrepupTimeZoneByCountry.
        /// </summary>
        internal static string Get_TimezonesByCountry {
            get {
                return ResourceManager.GetString("Get_TimezonesByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_TransactionExists.
        /// </summary>
        internal static string Get_TransactionExists {
            get {
                return ResourceManager.GetString("Get_TransactionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tm_Get_TrepmailAccount.
        /// </summary>
        internal static string Get_TrepmailAccount {
            get {
                return ResourceManager.GetString("Get_TrepmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_TSINCreateDetails_v2.
        /// </summary>
        internal static string Get_TSINCreateDetails {
            get {
                return ResourceManager.GetString("Get_TSINCreateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserAddress.
        /// </summary>
        internal static string Get_UserAddress {
            get {
                return ResourceManager.GetString("Get_UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserBirthday.
        /// </summary>
        internal static string Get_UserBirthday {
            get {
                return ResourceManager.GetString("Get_UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserCurrencyDetails.
        /// </summary>
        internal static string Get_UserCurrencyDetails {
            get {
                return ResourceManager.GetString("Get_UserCurrencyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserDetails_V1.
        /// </summary>
        internal static string Get_UserDetails {
            get {
                return ResourceManager.GetString("Get_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserDetailsByEmail_v1.
        /// </summary>
        internal static string Get_UserDetailsByEmail {
            get {
                return ResourceManager.GetString("Get_UserDetailsByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserDetailsBySocialID_v5.
        /// </summary>
        internal static string Get_UserDetailsBySocialID {
            get {
                return ResourceManager.GetString("Get_UserDetailsBySocialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserEmailCountForVerificationActivities_V1.
        /// </summary>
        internal static string Get_UserEmailCountForVerificationActivities {
            get {
                return ResourceManager.GetString("Get_UserEmailCountForVerificationActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserEmailDetailsByEmailIDUserID_V2.
        /// </summary>
        internal static string Get_UserEmailDetailsByEmailIDUserID {
            get {
                return ResourceManager.GetString("Get_UserEmailDetailsByEmailIDUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserExists.
        /// </summary>
        internal static string Get_UserExists {
            get {
                return ResourceManager.GetString("Get_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserGender_V1.
        /// </summary>
        internal static string Get_UserGender {
            get {
                return ResourceManager.GetString("Get_UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserHomeCountryDetails.
        /// </summary>
        internal static string Get_UserHomeCountryDetails {
            get {
                return ResourceManager.GetString("Get_UserHomeCountryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserCountry_v1.
        /// </summary>
        internal static string Get_UserLocation {
            get {
                return ResourceManager.GetString("Get_UserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserLogin_v5.
        /// </summary>
        internal static string Get_UserLogin {
            get {
                return ResourceManager.GetString("Get_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UsernameDetails.
        /// </summary>
        internal static string Get_UsernameDetails {
            get {
                return ResourceManager.GetString("Get_UsernameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UsernameExists.
        /// </summary>
        internal static string Get_UsernameExists {
            get {
                return ResourceManager.GetString("Get_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserOrderHistory.
        /// </summary>
        internal static string Get_UserOrderHistory {
            get {
                return ResourceManager.GetString("Get_UserOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserPasswordDetails.
        /// </summary>
        internal static string Get_UserPasswordDetails {
            get {
                return ResourceManager.GetString("Get_UserPasswordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserPreferrenceDetails_v2.
        /// </summary>
        internal static string Get_UserPreferrenceDetails {
            get {
                return ResourceManager.GetString("Get_UserPreferrenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserSession.
        /// </summary>
        internal static string Get_UserSession {
            get {
                return ResourceManager.GetString("Get_UserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_UserSubscriptionDetails.
        /// </summary>
        internal static string Get_UserSubscriptionDetails {
            get {
                return ResourceManager.GetString("Get_UserSubscriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Get_USINCreateDetails_v4.
        /// </summary>
        internal static string Get_USINCreateDetails {
            get {
                return ResourceManager.GetString("Get_USINCreateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_AbuseDetails.
        /// </summary>
        internal static string Insert_AbuseDetails {
            get {
                return ResourceManager.GetString("Insert_AbuseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_AccountDeactivationDetails.
        /// </summary>
        internal static string Insert_AccountDeactivationDetails {
            get {
                return ResourceManager.GetString("Insert_AccountDeactivationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_AccountDeletionDetails.
        /// </summary>
        internal static string Insert_AccountDeletionDetails {
            get {
                return ResourceManager.GetString("Insert_AccountDeletionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_AccountEmail.
        /// </summary>
        internal static string Insert_AccountEmail {
            get {
                return ResourceManager.GetString("Insert_AccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_Badge.
        /// </summary>
        internal static string Insert_Badge {
            get {
                return ResourceManager.GetString("Insert_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_DefaultUsername.
        /// </summary>
        internal static string Insert_DefaultUsername {
            get {
                return ResourceManager.GetString("Insert_DefaultUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_FreeStoreSubscription.
        /// </summary>
        internal static string Insert_FreeStoreSubscription {
            get {
                return ResourceManager.GetString("Insert_FreeStoreSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_InviteEmailDetails_v1.
        /// </summary>
        internal static string Insert_InviteEmailDetails {
            get {
                return ResourceManager.GetString("Insert_InviteEmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_OrderDetails_v6.
        /// </summary>
        internal static string Insert_Order {
            get {
                return ResourceManager.GetString("Insert_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_BillingAddress_v2.
        /// </summary>
        internal static string Insert_Payment_Address {
            get {
                return ResourceManager.GetString("Insert_Payment_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ReturnOrderItemDetails.
        /// </summary>
        internal static string Insert_ReturnOrderItemDetails {
            get {
                return ResourceManager.GetString("Insert_ReturnOrderItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ReviewComment.
        /// </summary>
        internal static string Insert_ReviewComment {
            get {
                return ResourceManager.GetString("Insert_ReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ShareEmailDetails_V7.
        /// </summary>
        internal static string Insert_ShareEmailDetails {
            get {
                return ResourceManager.GetString("Insert_ShareEmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ShareReport.
        /// </summary>
        internal static string Insert_ShareReport {
            get {
                return ResourceManager.GetString("Insert_ShareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ShareSubscribe.
        /// </summary>
        internal static string Insert_ShareSubscribe {
            get {
                return ResourceManager.GetString("Insert_ShareSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_ShareUnsubscribe.
        /// </summary>
        internal static string Insert_ShareUnsubscribe {
            get {
                return ResourceManager.GetString("Insert_ShareUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_SocialInviteStore_v1.
        /// </summary>
        internal static string Insert_SocialInviteStore {
            get {
                return ResourceManager.GetString("Insert_SocialInviteStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_Store_V1.
        /// </summary>
        internal static string Insert_Store {
            get {
                return ResourceManager.GetString("Insert_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_StoreActivityLog.
        /// </summary>
        internal static string Insert_StoreActivityLog {
            get {
                return ResourceManager.GetString("Insert_StoreActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_StoreCoverPhoto.
        /// </summary>
        internal static string Insert_StoreCoverPhoto {
            get {
                return ResourceManager.GetString("Insert_StoreCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_StoreFollower.
        /// </summary>
        internal static string Insert_StoreFollower {
            get {
                return ResourceManager.GetString("Insert_StoreFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_StorePostComment.
        /// </summary>
        internal static string Insert_StorePostComment {
            get {
                return ResourceManager.GetString("Insert_StorePostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_StorePostDetails_v1.
        /// </summary>
        internal static string Insert_StorePostDetails {
            get {
                return ResourceManager.GetString("Insert_StorePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_SystemMail.
        /// </summary>
        internal static string Insert_SystemMail {
            get {
                return ResourceManager.GetString("Insert_SystemMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tm_Insert_TrepmailAccount_v1.
        /// </summary>
        internal static string Insert_TrepmailAccount {
            get {
                return ResourceManager.GetString("Insert_TrepmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_UserActivityLog.
        /// </summary>
        internal static string Insert_UserActivityLog {
            get {
                return ResourceManager.GetString("Insert_UserActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_UserLoginLog.
        /// </summary>
        internal static string Insert_UserLoginLog {
            get {
                return ResourceManager.GetString("Insert_UserLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Insert_UserPreferrences.
        /// </summary>
        internal static string Insert_UserPreferrences {
            get {
                return ResourceManager.GetString("Insert_UserPreferrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_IsRestrictedName_V2.
        /// </summary>
        internal static string IsRestrictedName {
            get {
                return ResourceManager.GetString("IsRestrictedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Manage_ReviewCommentLike.
        /// </summary>
        internal static string Manage_ReviewCommentLike {
            get {
                return ResourceManager.GetString("Manage_ReviewCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Manage_ReviewLike.
        /// </summary>
        internal static string Manage_ReviewLike {
            get {
                return ResourceManager.GetString("Manage_ReviewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Manage_StorePostCommentLike.
        /// </summary>
        internal static string Manage_StorePostCommentLike {
            get {
                return ResourceManager.GetString("Manage_StorePostCommentLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Manage_StorePostLike.
        /// </summary>
        internal static string Manage_StorePostLike {
            get {
                return ResourceManager.GetString("Manage_StorePostLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Manage_StorePostMedia.
        /// </summary>
        internal static string Manage_StorePostMedia {
            get {
                return ResourceManager.GetString("Manage_StorePostMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_StoreNameGeoLocationCheck.
        /// </summary>
        internal static string StoreNameGeoLocationCheck {
            get {
                return ResourceManager.GetString("StoreNameGeoLocationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_AccountEmailVerificationCode.
        /// </summary>
        internal static string Update_AccountEmailVerificationCode {
            get {
                return ResourceManager.GetString("Update_AccountEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_AvgRatingAndUserRateCount_V1.
        /// </summary>
        internal static string Update_AvgRatingAndUserRateCount {
            get {
                return ResourceManager.GetString("Update_AvgRatingAndUserRateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_CancelAccountDeletionDetails.
        /// </summary>
        internal static string Update_CancelAccountDeletionDetails {
            get {
                return ResourceManager.GetString("Update_CancelAccountDeletionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_ProductGroupName.
        /// </summary>
        internal static string Update_GroupName {
            get {
                return ResourceManager.GetString("Update_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_InviteFollowAndVerify.
        /// </summary>
        internal static string Update_InvitedUserDetails {
            get {
                return ResourceManager.GetString("Update_InvitedUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_LoginAttemptTracking.
        /// </summary>
        internal static string Update_LoginAttemptTracking {
            get {
                return ResourceManager.GetString("Update_LoginAttemptTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_LogOutTimeLog.
        /// </summary>
        internal static string Update_LogOutTimeLog {
            get {
                return ResourceManager.GetString("Update_LogOutTimeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_NameDetails.
        /// </summary>
        internal static string Update_NameDetails {
            get {
                return ResourceManager.GetString("Update_NameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_OrderDetailsBeforeTransaction.
        /// </summary>
        internal static string Update_OrderDetailsBeforeTransaction {
            get {
                return ResourceManager.GetString("Update_OrderDetailsBeforeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_OrderItemStatus.
        /// </summary>
        internal static string Update_OrderItemStatus {
            get {
                return ResourceManager.GetString("Update_OrderItemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_Password.
        /// </summary>
        internal static string Update_Password {
            get {
                return ResourceManager.GetString("Update_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_PasswordAttemptTracking.
        /// </summary>
        internal static string Update_PasswordAttemptTracking {
            get {
                return ResourceManager.GetString("Update_PasswordAttemptTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_PreviousNameDetails.
        /// </summary>
        internal static string Update_PreviousNameDetails {
            get {
                return ResourceManager.GetString("Update_PreviousNameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_ProductRank_V3.
        /// </summary>
        internal static string Update_ProductRank {
            get {
                return ResourceManager.GetString("Update_ProductRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_QRImage_v1.
        /// </summary>
        internal static string Update_QRImage {
            get {
                return ResourceManager.GetString("Update_QRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_ReactivateUserAccount_V4.
        /// </summary>
        internal static string Update_ReactivateUserAccount {
            get {
                return ResourceManager.GetString("Update_ReactivateUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_Review_V3.
        /// </summary>
        internal static string Update_Review {
            get {
                return ResourceManager.GetString("Update_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_ReviewComment.
        /// </summary>
        internal static string Update_ReviewComment {
            get {
                return ResourceManager.GetString("Update_ReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_ReviewStarRating_V3.
        /// </summary>
        internal static string Update_ReviewStarRating {
            get {
                return ResourceManager.GetString("Update_ReviewStarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_SearchIndexedToElastic.
        /// </summary>
        internal static string Update_SearchIndexedToElastic {
            get {
                return ResourceManager.GetString("Update_SearchIndexedToElastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_SSIN.
        /// </summary>
        internal static string Update_SSIN {
            get {
                return ResourceManager.GetString("Update_SSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreCategory.
        /// </summary>
        internal static string Update_StoreCategory {
            get {
                return ResourceManager.GetString("Update_StoreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreCoverPhoto.
        /// </summary>
        internal static string Update_StoreCoverPhoto {
            get {
                return ResourceManager.GetString("Update_StoreCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreDescription.
        /// </summary>
        internal static string Update_StoreDescription {
            get {
                return ResourceManager.GetString("Update_StoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreFollower.
        /// </summary>
        internal static string Update_StoreFollower {
            get {
                return ResourceManager.GetString("Update_StoreFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreHeadcount.
        /// </summary>
        internal static string Update_StoreHeadcount {
            get {
                return ResourceManager.GetString("Update_StoreHeadcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreHours.
        /// </summary>
        internal static string Update_StoreHours {
            get {
                return ResourceManager.GetString("Update_StoreHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreLocationDetails.
        /// </summary>
        internal static string Update_StoreLocation {
            get {
                return ResourceManager.GetString("Update_StoreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreMetrics.
        /// </summary>
        internal static string Update_StoreMetrics {
            get {
                return ResourceManager.GetString("Update_StoreMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreName.
        /// </summary>
        internal static string Update_StoreName {
            get {
                return ResourceManager.GetString("Update_StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreNameToPreviousName.
        /// </summary>
        internal static string Update_StoreNameToPreviousName {
            get {
                return ResourceManager.GetString("Update_StoreNameToPreviousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreOpeningDate.
        /// </summary>
        internal static string Update_StoreOpeningDate {
            get {
                return ResourceManager.GetString("Update_StoreOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StorePhoneNumber.
        /// </summary>
        internal static string Update_StorePhoneNumber {
            get {
                return ResourceManager.GetString("Update_StorePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StorePostComment.
        /// </summary>
        internal static string Update_StorePostComment {
            get {
                return ResourceManager.GetString("Update_StorePostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StorePostDetails.
        /// </summary>
        internal static string Update_StorePostDetails {
            get {
                return ResourceManager.GetString("Update_StorePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StorePostMedia.
        /// </summary>
        internal static string Update_StorePostMedia {
            get {
                return ResourceManager.GetString("Update_StorePostMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreProfilePicture.
        /// </summary>
        internal static string Update_StoreProfilePicture {
            get {
                return ResourceManager.GetString("Update_StoreProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreSocialLinks.
        /// </summary>
        internal static string Update_StoreSocialLinks {
            get {
                return ResourceManager.GetString("Update_StoreSocialLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreUsername.
        /// </summary>
        internal static string Update_StoreUsername {
            get {
                return ResourceManager.GetString("Update_StoreUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_StoreWebsite_v1.
        /// </summary>
        internal static string Update_StoreWebsite {
            get {
                return ResourceManager.GetString("Update_StoreWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_OrderDetails_V4.
        /// </summary>
        internal static string Update_TransactionDetails {
            get {
                return ResourceManager.GetString("Update_TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_TranscodedVideos_v1.
        /// </summary>
        internal static string Update_TranscodedVideos {
            get {
                return ResourceManager.GetString("Update_TranscodedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_TrepupAccountEmail.
        /// </summary>
        internal static string Update_TrepupAccountEmail {
            get {
                return ResourceManager.GetString("Update_TrepupAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserAddressPriority.
        /// </summary>
        internal static string Update_UserAddressPriority {
            get {
                return ResourceManager.GetString("Update_UserAddressPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserBirthday.
        /// </summary>
        internal static string Update_UserBirthday {
            get {
                return ResourceManager.GetString("Update_UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserCode_v2.
        /// </summary>
        internal static string Update_UserCode {
            get {
                return ResourceManager.GetString("Update_UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserGender_V1.
        /// </summary>
        internal static string Update_UserGender {
            get {
                return ResourceManager.GetString("Update_UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UsernameDetails.
        /// </summary>
        internal static string Update_UsernameDetails {
            get {
                return ResourceManager.GetString("Update_UsernameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserProfilePicture.
        /// </summary>
        internal static string Update_UserProfilePicture {
            get {
                return ResourceManager.GetString("Update_UserProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserSessionLogOutTime.
        /// </summary>
        internal static string Update_UserSessionLogOutTime {
            get {
                return ResourceManager.GetString("Update_UserSessionLogOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserSocialToken_V1.
        /// </summary>
        internal static string Update_UserSocialToken {
            get {
                return ResourceManager.GetString("Update_UserSocialToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_UserTimezone.
        /// </summary>
        internal static string Update_UserTimezone {
            get {
                return ResourceManager.GetString("Update_UserTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_USIN_v2.
        /// </summary>
        internal static string Update_USIN {
            get {
                return ResourceManager.GetString("Update_USIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Update_VerifyAccountEmail.
        /// </summary>
        internal static string Update_VerifyAccountEmail {
            get {
                return ResourceManager.GetString("Update_VerifyAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tu_Validate_IndianPincodeWithState.
        /// </summary>
        internal static string Validate_IndianPincodeWithState {
            get {
                return ResourceManager.GetString("Validate_IndianPincodeWithState", resourceCulture);
            }
        }
    }
}
